#!/bin/sh
set -eu

# Prepare a Debian machine to boot Grml Rescue from local disk via GRUB.
# Public-safe: this script contains no private IPs, hostnames, or passwords.
# Run as root on the Debian box you want to prepare:
#   sh grml-rescue-setup.sh

GRML_DIR="/boot/grml"
GRML_DEFAULTS="/etc/default/grml-rescueboot"

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

info() {
  printf '==> %s\n' "$*"
}

warn() {
  printf 'WARNING: %s\n' "$*" >&2
}

need_root() {
  [ "$(id -u)" = "0" ] || die "Run this script as root."
}

cmd_exists() {
  command -v "$1" >/dev/null 2>&1
}

clean_answer() {
  bs="$(printf '\010')"
  del="$(printf '\177')"
  cr="$(printf '\015')"
  printf "%s" "$1" | sed \
    -e "s/$cr//g" \
    -e ":again" \
    -e "s/.[${bs}${del}]//g" \
    -e "t again" \
    -e "s/[${bs}${del}]//g" \
    -e 's/^[[:space:]]*//' \
    -e 's/[[:space:]]*$//'
}

ask() {
  prompt="$1"
  default="$2"
  if [ -n "$default" ]; then
    printf '\n[Q] %s\n[Answer] [%s]: ' "$prompt" "$default" >&2
  else
    printf '\n[Q] %s\n[Answer]: ' "$prompt" >&2
  fi
  read -r ans || ans=""
  ans="$(clean_answer "$ans")"
  [ -n "$ans" ] || ans="$default"
  printf "%s" "$ans"
}

ask_secret() {
  prompt="$1"
  printf '\n[Q] %s\n[Answer hidden; leave empty to skip]: ' "$prompt" >&2
  if [ -t 0 ]; then
    stty_orig="$(stty -g 2>/dev/null || true)"
    stty -echo 2>/dev/null || true
    read -r ans || ans=""
    [ -z "$stty_orig" ] || stty "$stty_orig" 2>/dev/null || true
    printf '\n' >&2
  else
    read -r ans || ans=""
  fi
  clean_answer "$ans"
}

ask_yn() {
  prompt="$1"
  default="$2"
  case "$default" in
    y|Y|yes|YES|Yes) suffix="Y/n"; default="y" ;;
    n|N|no|NO|No) suffix="y/N"; default="n" ;;
    *) suffix="y/N"; default="n" ;;
  esac

  while :; do
    printf '\n[Q] %s\n[Answer] (%s): ' "$prompt" "$suffix" >&2
    read -r ans || ans=""
    ans="$(clean_answer "$ans")"
    [ -n "$ans" ] || ans="$default"
    case "$ans" in
      y|Y|yes|YES|Yes) return 0 ;;
      n|N|no|NO|No) return 1 ;;
      *) printf 'Please answer yes or no.\n' >&2 ;;
    esac
  done
}

major_version() {
  printf '%s' "$1" | sed 's/[^0-9].*$//'
}

check_os() {
  [ -r /etc/os-release ] || die "/etc/os-release not found; cannot verify OS."
  # shellcheck disable=SC1091
  . /etc/os-release
  id="${ID:-}"
  version_id="${VERSION_ID:-0}"
  major="$(major_version "$version_id")"

  [ "$id" = "debian" ] || die "This script supports Debian only. Detected ID='$id'."
  [ "${major:-0}" -ge 11 ] || die "Debian version must be >= 11. Detected VERSION_ID='$version_id'."
  info "OS check passed: ${PRETTY_NAME:-$id $version_id}"
}

check_bootloader() {
  cmd_exists update-grub || die "update-grub is missing. Install/configure GRUB first."
  cmd_exists grub-reboot || warn "grub-reboot is missing; setup can continue, but one-time boot staging may not work."
  [ -d /boot/grub ] || die "/boot/grub not found. This script expects GRUB 2."
}

install_packages() {
  info "Installing grml-rescueboot and verification tools."
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y grml-rescueboot debian-keyring gpgv wget
}

download_grml_small() {
  info "Downloading and verifying the latest grml-small ISO."
  update-grml-rescueboot -t small
}

validate_token() {
  name="$1"
  value="$2"
  case "$value" in
    *[!A-Za-z0-9._:@%+=,/-]*)
      die "$name contains unsupported characters. Avoid spaces, quotes, shell metacharacters, and backslashes."
      ;;
  esac
}

validate_hostname() {
  value="$1"
  [ -n "$value" ] || die "Hostname cannot be empty."
  [ "${#value}" -le 63 ] || die "Hostname must be 63 characters or less."
  case "$value" in
    *[!A-Za-z0-9.-]*)
      die "Hostname may contain only letters, numbers, dots, and hyphens."
      ;;
    -*|*-|.*|*.)
      die "Hostname must not start or end with a dot or hyphen."
      ;;
  esac
}

write_grml_defaults() {
  boot_options="$1"

  timestamp="$(date +%Y%m%d%H%M%S)"
  if [ -e "$GRML_DEFAULTS" ]; then
    cp -a "$GRML_DEFAULTS" "$GRML_DEFAULTS.bak.$timestamp"
    info "Backed up $GRML_DEFAULTS to $GRML_DEFAULTS.bak.$timestamp"
  fi

  cat >"$GRML_DEFAULTS" <<EOF
## Configuration file for Debian package grml-rescueboot.
## Managed by grml-rescue-setup.sh.

# Location of ISOs:
# ISO_LOCATION="$GRML_DIR/"

# Boot options passed to Grml ISO entries generated by update-grub.
CUSTOM_BOOTOPTIONS='$boot_options'
EOF
}

configure_grml_options() {
  current_host="$(hostname 2>/dev/null || printf 'debian')"
  default_grml_host="${current_host}-grml"

  grml_host="$(ask "Hostname to use while booted into Grml" "$default_grml_host")"
  validate_hostname "$grml_host"

  use_toram="n"
  if ask_yn "Copy Grml into RAM with toram? Recommended for disk imaging/rescue work." "y"; then
    use_toram="y"
  fi

  warn "If you set an SSH password here, it will be stored in $GRML_DEFAULTS and /boot/grub/grub.cfg."
  warn "Use a temporary rescue password, and remove or rotate it after you are done."
  ssh_password="$(ask_secret "Temporary Grml SSH password")"
  if [ -n "$ssh_password" ]; then
    validate_token "SSH password" "$ssh_password"
    boot_options="ssh=$ssh_password hostname=$grml_host"
  else
    boot_options="ssh hostname=$grml_host"
  fi

  if [ "$use_toram" = "y" ]; then
    boot_options="$boot_options toram"
  fi

  write_grml_defaults "$boot_options"
  info "Configured Grml boot options: $boot_options"
}

update_grub_config() {
  info "Regenerating GRUB configuration."
  update-grub
}

grml_entry_name() {
  grep '^menuentry "Grml Rescue System' /boot/grub/grub.cfg \
    | sed -n 's/^menuentry "\([^"]*\)".*/\1/p' \
    | head -n 1
}

show_status() {
  entry="$(grml_entry_name || true)"

  printf '\n'
  info "Setup complete."
  printf 'Grml ISO files:\n'
  ls -lh "$GRML_DIR"/*.iso 2>/dev/null || true

  if [ -n "$entry" ]; then
    printf '\nGRUB entry:\n  %s\n' "$entry"
    printf '\nTo boot Grml one time later, run:\n'
    printf "  grub-reboot '%s'\n" "$entry"
    printf '  reboot\n'
  else
    warn "No Grml GRUB entry was found. Check update-grub output above."
  fi
}

maybe_stage_one_time_boot() {
  entry="$(grml_entry_name || true)"
  [ -n "$entry" ] || return 0
  cmd_exists grub-reboot || return 0

  if ask_yn "Stage the Grml entry for the next boot only? This does not reboot now." "n"; then
    grub-reboot "$entry"
    info "Next boot is staged for: $entry"
    info "Run 'reboot' when ready."
  fi
}

main() {
  need_root
  check_os
  check_bootloader
  install_packages
  download_grml_small
  configure_grml_options
  update_grub_config
  show_status
  maybe_stage_one_time_boot
}

main "$@"
